added typescript to the project and basic types
yactouat/SWS_waste-sorter pull request #42
Opened 2023-06-27 17:52 UTC by etnms

I added a basic typescript config (plus the type dependencies in package.json), as well as basic types into the frontend.

2023-06-27 19:53 UTC, yactouat requested changes
hey @etnms , thank you for contribution and your time !

I just read your PR, can you tell me please if you encountered this issue on `npm install` =>

```bash
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-scripts@5.0.1
npm ERR! Found: typescript@5.1.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^5.1.3" from the root project
npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm ERR!   node_modules/fork-ts-checker-webpack-plugin
npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm ERR!     node_modules/react-dev-utils
npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm ERR!       node_modules/react-scripts
npm ERR!         react-scripts@"^5.0.1" from the root project
npm ERR!   1 more (tsutils)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"^5.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"^5.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It seems that some packages are conflicting, steps to reproduce:
- I've cloned your fork
- I've checked out the Typescript branch
- `npm install`

Cheers,

Yacine

2023-06-27 19:53 UTC, yactouat commented on frontend/package.json
> +    "@types/jest": "^29.5.2",
hey @etnms , thank you for your contribution ! to reduce the size of the prod bundle on app' build, it would be preferable to add the `@types/xxx` libs in the dev dependencies ;)

2023-06-27 19:53 UTC, yactouat commented on frontend/tsconfig.json
> +    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
do you think we can chose a more recent target without too much overhead here ?

2023-06-27 19:54 UTC, yactouat commented
also, I've just merged another PR, please rebase on your branch or pull the latest main so there are no conflicts ;)

2023-06-27 21:56 UTC, etnms commented on frontend/package.json
> +    "@types/jest": "^29.5.2",
Hey you're right, I'll fix that

2023-06-27 22:01 UTC, etnms commented on frontend/tsconfig.json
> +    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
Honestly, not sure. I always stick to es5 or es6, rarely above (to ensure compatibility, make sure it works with older browsers etc.), andI can't really tell you if a more recent would be too much for this project.

2023-06-27 22:09 UTC, etnms commented
> hey @etnms , thank you for contribution and your time !
> 
> I just read your PR, can you tell me please if you encountered this issue on `npm install` =>
> 
> ```shell
> $ npm install
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: react-scripts@5.0.1
> npm ERR! Found: typescript@5.1.3
> npm ERR! node_modules/typescript
> npm ERR!   dev typescript@"^5.1.3" from the root project
> npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
> npm ERR!   node_modules/fork-ts-checker-webpack-plugin
> npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
> npm ERR!     node_modules/react-dev-utils
> npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
> npm ERR!       node_modules/react-scripts
> npm ERR!         react-scripts@"^5.0.1" from the root project
> npm ERR!   1 more (tsutils)
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
> npm ERR! node_modules/react-scripts
> npm ERR!   react-scripts@"^5.0.1" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: typescript@4.9.5
> npm ERR! node_modules/typescript
> npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
> npm ERR!   node_modules/react-scripts
> npm ERR!     react-scripts@"^5.0.1" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ```
> 
> It seems that some packages are conflicting, steps to reproduce:
> 
> * I've cloned your fork
> * I've checked out the Typescript branch
> * `npm install`
> 
> Cheers,
> 
> Yacine

Thanks for letting me know. I changed the typescript version to 4.7.4 which seems to be working just fine now. It seems that there was some conflict between typescript and react-script, but I don't really know why even after looking at it.

2023-06-28 04:25 UTC, yactouat commented on frontend/tsconfig.json
> +    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
alright !

2023-06-28 04:34 UTC, yactouat approved these changes
thanks again for your contribution !

2023-06-28 04:34 UTC, merged